### ISSUE TITLE
Array format in query string parameters

### ISSUE THREAD

**Issue by javierbrea** [data-provider/axios#6]
Currently, when passing an array to a query string parameter it is always stringified as a list separated by commas.

It is desirable that this behavior can be configured to use another array formats, such as in the query-string npm package

For doing this, a new configuration option called queryStringArrayFormat could be added:

```js
import { Api } from "@data-provider/axios";

const myApi =  new Api("/foo-url", {
  queryStringArrayFormat: "none"
});

fooApi.query({
  queryString: { foo: [1, 2, 3] }
}).read();

//=> 'foo=1,2'
```
Available formats could be the same than in the query-string npm package:

* 'bracket': Serialize arrays using bracket representation:
```js
//=> 'foo[]=1&foo[]=2&foo[]=3'
```
* 'index': Serialize arrays using index representation:
```js
//=> 'foo[0]=1&foo[1]=2&foo[3]=3'
```
* 'comma': Serialize arrays by separating elements with comma (default behavior until next major version for maintaining retrocompatibility):
```js
//=> 'foo=1,2,3'
```
* 'none': Serialize arrays by using duplicate keys (default behavior in next major version):
```js
//=> 'foo=1&foo=2&foo=3'
```

**Comment by javierbrea** [comment]
This issue was originally created at XByOrange/mercury-api#9. That project seems to be no longer maintained, so it should be fixed in this one.

**Comment by caox2110** [comment]
Is this bug already fixed in this project? In which version?

**Comment by javierbrea** [comment]
Hi @caox2110 , no, still not. It was only an idea for a possible enhancement, but no one has really needed it... until now. So I will prioritize it. 😃

**Comment by javierbrea** [comment]
Hi again @caox2110 ,
This enhancement has been published in the [v4.0.0 release](https://github.com/data-provider/axios/releases/tag/v4.0.0). Note that it is a breaking change because now query strings are formatted using the default options from the `query-string` package, which affects to the format in which arrays are serialized.
